/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as RandomUsersRouteImport } from './routes/randomUsers'
import { Route as RandomCatsRouteImport } from './routes/randomCats'
import { Route as ECommerceRouteImport } from './routes/eCommerce'
import { Route as IndexRouteImport } from './routes/index'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomUsersRoute = RandomUsersRouteImport.update({
  id: '/randomUsers',
  path: '/randomUsers',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomCatsRoute = RandomCatsRouteImport.update({
  id: '/randomCats',
  path: '/randomCats',
  getParentRoute: () => rootRouteImport,
} as any)
const ECommerceRoute = ECommerceRouteImport.update({
  id: '/eCommerce',
  path: '/eCommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eCommerce': typeof ECommerceRoute
  '/randomCats': typeof RandomCatsRoute
  '/randomUsers': typeof RandomUsersRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eCommerce': typeof ECommerceRoute
  '/randomCats': typeof RandomCatsRoute
  '/randomUsers': typeof RandomUsersRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eCommerce': typeof ECommerceRoute
  '/randomCats': typeof RandomCatsRoute
  '/randomUsers': typeof RandomUsersRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eCommerce' | '/randomCats' | '/randomUsers' | '/youtube'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eCommerce' | '/randomCats' | '/randomUsers' | '/youtube'
  id:
    | '__root__'
    | '/'
    | '/eCommerce'
    | '/randomCats'
    | '/randomUsers'
    | '/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ECommerceRoute: typeof ECommerceRoute
  RandomCatsRoute: typeof RandomCatsRoute
  RandomUsersRoute: typeof RandomUsersRoute
  YoutubeRoute: typeof YoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomUsers': {
      id: '/randomUsers'
      path: '/randomUsers'
      fullPath: '/randomUsers'
      preLoaderRoute: typeof RandomUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomCats': {
      id: '/randomCats'
      path: '/randomCats'
      fullPath: '/randomCats'
      preLoaderRoute: typeof RandomCatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eCommerce': {
      id: '/eCommerce'
      path: '/eCommerce'
      fullPath: '/eCommerce'
      preLoaderRoute: typeof ECommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ECommerceRoute: ECommerceRoute,
  RandomCatsRoute: RandomCatsRoute,
  RandomUsersRoute: RandomUsersRoute,
  YoutubeRoute: YoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
