/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as RandomUsersRouteImport } from './routes/randomUsers'
import { Route as RandomCatsRouteImport } from './routes/randomCats'
import { Route as QuotesListnerRouteImport } from './routes/quotesListner'
import { Route as ProductListRouteImport } from './routes/productList'
import { Route as JokesViewerRouteImport } from './routes/jokesViewer'
import { Route as IndexRouteImport } from './routes/index'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomUsersRoute = RandomUsersRouteImport.update({
  id: '/randomUsers',
  path: '/randomUsers',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomCatsRoute = RandomCatsRouteImport.update({
  id: '/randomCats',
  path: '/randomCats',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesListnerRoute = QuotesListnerRouteImport.update({
  id: '/quotesListner',
  path: '/quotesListner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductListRoute = ProductListRouteImport.update({
  id: '/productList',
  path: '/productList',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesViewerRoute = JokesViewerRouteImport.update({
  id: '/jokesViewer',
  path: '/jokesViewer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jokesViewer': typeof JokesViewerRoute
  '/productList': typeof ProductListRoute
  '/quotesListner': typeof QuotesListnerRoute
  '/randomCats': typeof RandomCatsRoute
  '/randomUsers': typeof RandomUsersRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jokesViewer': typeof JokesViewerRoute
  '/productList': typeof ProductListRoute
  '/quotesListner': typeof QuotesListnerRoute
  '/randomCats': typeof RandomCatsRoute
  '/randomUsers': typeof RandomUsersRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jokesViewer': typeof JokesViewerRoute
  '/productList': typeof ProductListRoute
  '/quotesListner': typeof QuotesListnerRoute
  '/randomCats': typeof RandomCatsRoute
  '/randomUsers': typeof RandomUsersRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jokesViewer'
    | '/productList'
    | '/quotesListner'
    | '/randomCats'
    | '/randomUsers'
    | '/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jokesViewer'
    | '/productList'
    | '/quotesListner'
    | '/randomCats'
    | '/randomUsers'
    | '/youtube'
  id:
    | '__root__'
    | '/'
    | '/jokesViewer'
    | '/productList'
    | '/quotesListner'
    | '/randomCats'
    | '/randomUsers'
    | '/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JokesViewerRoute: typeof JokesViewerRoute
  ProductListRoute: typeof ProductListRoute
  QuotesListnerRoute: typeof QuotesListnerRoute
  RandomCatsRoute: typeof RandomCatsRoute
  RandomUsersRoute: typeof RandomUsersRoute
  YoutubeRoute: typeof YoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomUsers': {
      id: '/randomUsers'
      path: '/randomUsers'
      fullPath: '/randomUsers'
      preLoaderRoute: typeof RandomUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomCats': {
      id: '/randomCats'
      path: '/randomCats'
      fullPath: '/randomCats'
      preLoaderRoute: typeof RandomCatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotesListner': {
      id: '/quotesListner'
      path: '/quotesListner'
      fullPath: '/quotesListner'
      preLoaderRoute: typeof QuotesListnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productList': {
      id: '/productList'
      path: '/productList'
      fullPath: '/productList'
      preLoaderRoute: typeof ProductListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokesViewer': {
      id: '/jokesViewer'
      path: '/jokesViewer'
      fullPath: '/jokesViewer'
      preLoaderRoute: typeof JokesViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JokesViewerRoute: JokesViewerRoute,
  ProductListRoute: ProductListRoute,
  QuotesListnerRoute: QuotesListnerRoute,
  RandomCatsRoute: RandomCatsRoute,
  RandomUsersRoute: RandomUsersRoute,
  YoutubeRoute: YoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
